name: Remove TikTok from Schema

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - '.github/workflows/fix-tiktok.yml'

jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
      - name: Remove TikTok
        env:
          PAT: ${{ secrets.SATELLITE_DEPLOY_TOKEN }}
        run: |
          git clone https://x-access-token:${PAT}@github.com/carpentraspizzanapoli-design/pizza-napoli.git site
          cd site
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          sed -i 's|,"https://www.tiktok.com/@pizzanapolicarpentras"||g' index.html
          echo "Removed TikTok"

          git add index.html
          git commit -m "Remove TikTok link from Schema.org"
          git push origin main
